---
output: 
 pdf_document:
    keep_tex: TRUE
geometry: "left=2.5cm,right=2.5cm,top=2cm,bottom=2cm"
classoption: 11pt
header-includes:
  - \usepackage{nopageno}
---

Human Resources Management Group  
AJR/RS 2/04530/BEOE  
Room 2217, Corning Tower Building  
Empire State Plaza  
Albany, New York 12237-0012  
15 November 2021

$~$

To whom it may concern,

I am writing to apply to the position of Research Scientist 2 with the Bureau of Environmental & Occupational Epidemiology (BEOE) posted on the State Employment website. I am a 7th year doctoral student in Epidemiology at the University at Albany School of Public Health, where I took classes in epidemiology, biostatistics, data collection and analysis, Geographic Information Systems (GIS), and SAS. For my dissertation, I am analyzing the relationship between air pollution and select birth defects in New York State (NYS). 

In my current position, one of my longest projects is membership in the CDC EPHT Community Design Workgroup. I had studied urban policy and built environment, notably green space, in my Masters program, so it is a good fit for me. In this workgroup, I served on two separate subteams. On the food environment subteam, I assessed the usability of the InfoUSA business database to identify food service establishments using as my test case an area in Buffalo that we were investigating at the time as part of a cancer project. My assessment included research into the reliability of InfoUSA and mapping of the area in Buffalo using both food desert and food swamp calculations. Based partly on my analysis, both the workgroup and the project decided not to use the InfoUSA data. For this project, I reviewed literature, worked with diverse partners, and evaluated potential data sources.

On the traffic safety subteam, I assisted to develop a set of traffic fatality indicators using the Fatality Analysis Reporting System (FARS) database. I had used this database previously in a class project and was using at the time to write an R workshop on managing relational databases as part of the Epidemiology and Biostatistics Community of Practice (EBCoP) Learning Pathways program. After the Community Design subteams were dissolved, I tested the ArcGIS how-to guides to create the indicators proposed by each of the subteams, beginning with the traffic safety indicator. For this project, I am working closely with partners in Oregon and New Jersey to translate ArcGIS instructions to R and to improve indicator documentation.

I am developing an R package containing code modeled on the ArcGIS guides for all of the Community Design indicators with assistance from R programmers in other EPHT states. The traffic fatality indicators were recently completed and have been submitted to the CDC EPHT program for review as nationally consistent data measures to be displayed on the CDC Data Explorer or on individual states' data portals. The other indicators proposed by the workgroup are being polished now. For this project, I created a shared GitHub repository for the R programmers, all from other states, and have met with them outside workgroup meetings to coordinate package development.

I can bring to the Research Scientist 2 position at BEOE my expertise in data management, study design and analysis, written and oral communication, GIS, software and technical documentation development, and mentoring, and help increase the productivity of other team members.

Thank you in advance for your time and consideration. I can be reached at astamm@albany.edu or at 315-297-0987, email preferred.

Sincerely,  
Abigail Stamm
