---
output: 
 pdf_document:
    keep_tex: TRUE
geometry: "left=2.5cm,right=2.5cm,top=2cm,bottom=2cm"
header-includes:
  - \usepackage{nopageno}
---

# Abigail Stamm 

Phone: 315-297-0987  
Email: astamm@albany.edu  
LinkedIn: https://www.linkedin.com/in/abigail-stamm-3932765/ 

---

### SKILLS

*Geographic information systems:* MapMarker, ArcGIS, Geographic Aggregation Tool (GAT)  
*Programming languages:* R, SQL, SAS  
*Databases:* Statewide Planning and Research Cooperative System (SPARCS), NYS/NYC Vital Records, All-Payer Database (APD), Electronic Clinical Laboratory Reporting System (ECLRS), InfoUSA, Fatality Analysis Reporting System (FARS)  
*Markup languages:* Markdown, HTML, LaTeX, Roxygen  
*Graphic design:* GIMP, InkScape, Scribus   
*Mentorship:* public speaking, leadership, R programming  

---

### EXPERIENCE 

**Research Scientist**, March 2018 – Present  
Environmental Public Health Tracking Program, Bureau of Environmental & Occupational Epidemiology, NYS Department of Health, Albany, NY  

* *Data management and analysis*
    * Develop and manage a database of health and environmental data for the online data portal and write the data dictionary, schema, and documentation.
    * Validate datasets for CDC data submissions, the vaping project, the COVID nursing home project, and internal SPARCS data requests.
    * Summarize data and run weekly reports for the vaping and COVID sewershed projects.
    * Prepare health data for partner agencies based on subcounty areas developed using GAT.
    * Geocode addresses, spatially link data, and perform spatial analyses.
    * Assess feasibility of calculating food swamps using InfoUSA and of displaying subcounty-level birth measures.
* *Research and writing*
    * Review and summarize published literature on food swamp assessment, pest triggers of asthma, and associations between air pollution and birth defects.
    * Identify data and prepare maps and charts for special reports on asthma and cancer.
    * Co-prepare the institutional review board renewal for birth data and the NYS and NYC vital records data requests.
* *Training and leadership*
    * Train junior staff to geocode, use GAT, and assess data issues.
    * Co-lead CDC EPHT Differential Privacy Workgroup and participate in Hospitalization, Geospatial, Community Design, Cold Related Illness, and Systems & Network Development workgroups.
* *Software development*
    * Develop and maintain the GAT R package and its documentation and provide GAT support.
    * Develop and test proposed traffic safety measures and build an R package to calculate them.
    * Port SAS imputation code to R, develop a method for handling imputation results, and provide support for staff using R.
    * Liaise with IT partner to develop the NYS EPHT data portal and troubleshoot data issues.

**Data Analyst**, May 2016 – March 2018  
Bureau of Environmental & Occupational Epidemiology, NYS Department of Health, Albany, NY  

* Cleaned and analyzed 10 years of hospital data and 5 years of mortality data.
*	Geocoded 10 years of statewide heart attack data.
*	Designed 2 studies on heart attacks and wrote 2 manuscripts on the results.

**Evaluation Specialist**, June 2015 – March 2018  
Office of Program Evaluation and Research, AIDS Institute, NYS Department of Health, Albany, NY  

*	Managed the public safety naloxone use database, oversaw data entry, ran routine data validation checks, and called reporting agencies to resolve inconsistent data.
* Wrote a user's manual for the public safety naloxone use database.
*	Wrote 4 factsheets and a slideshow on naloxone usage projects.
*	Produced monthly and quarterly summary reports, and revised and formatted 1 state report and 2 articles, on naloxone use. 
* Trained staff to perform data entry and to use R and Scribus.

```{r eval = FALSE, echo=FALSE}
What they want:

* master’s or higher-level degree in public health or environmental health/science, epidemiology, statistics, biostatistics, mathmatics, or another closely related field. 
* Experience in environmental, occupational, disaster, and/or reproductive epidemiologic research is preferred, as well as exposure assessment, identification and surveillance of adverse health outcomes, and environmental risk factors of disease. 
* proficient in the collection, *management*, *linkage*, and *analysis* of environmental and human health data; 
* excellent written and oral communication skills for diverse audiences; 
* strong analytical, organizational, and interpersonal skills. 
* Knowledge of geographical information systems (GIS), SAS, R, Tableau, and working with large datasets is desirable. 
* proficiency in the use of Microsoft Excel, Word, Access, and PowerPoint, 
* ability to work independently, as well as in a team environment.

* provide statistical and epidemiologic support to various projects, including but not limited to biomonitoring, birth defects surveillance, and surveillance associated with emerging issues. 
* participate in various phases of epidemiological research, including: problem definition, literature review, study design, executing research plans, acquiring and managing relevant data, statistical/spatial/temporal analyses, summarizing findings, interpreting and sharing results, and preparing grant proposals, reports, and publications. 
* participating in various environmental, occupational, and reproductive health studies to determine risk factors of disease; 
* monitoring and evaluating the health effects of exposure to toxic substances at home, at work, and in the community; 
* assistance with exposure investigations and surveillance to identify and reduce health risks. 
* incorporate GIS to map disease and risk factors; 
* conduct environmental public health surveillance; 
* liaise with other state/federal agencies towards coordinating epidemiologic investigations; 
* provide public health education regarding health risks; 
* provide technical support and training to junior level research staff.
```

---

### EDUCATION 

PhD, Epidemiology, 2014 - present, School of Public Health, SUNY Albany, Albany, NY  
MA, Science, Health, and Environmental Communication, Marquette University, Milwaukee, WI  
BA, Anthropology, St Lawrence University, Canton, NY 

---

### ACTIVITIES 

* District 53 Toastmasters: Pathways Guide and Ambassador, 2018 
* Empire Toastmasters: Vice President Education,  2017 - 2018; Member, 2015 - present
* Capital Advanced Toastmasters: Sergeant at Arms,  2017 - 2018; Member, 2016 - 2020
* Epidemiology and Biostatistics Community of Practice, NYS Department of Health, 2016 - present
    * Co-chaired Learning Pathways Committee March 2016 – March 2020
    * Facilitated biannual R programming workshops at SUNY Albany
    * Coordinated ArcGIS, Python, and manuscript writing workshops

---

### PRESENTATIONS AND PUBLICATIONS

* Stamm, A, Muscatiello, N, & Hsu, W (2021). Accounting for demographics in geographic aggregation. Place & Health Conference 2021. Virtual, November 16, 2021. 
* Stamm, A (2021). gatpkg: Developing a geographic aggregation tool in R for non-programmers. useR! 2021. Virtual, July 6, 2021. 
* Stamm, A (2021). Geographic Aggregation Tool (GAT): A method for handling small numbers when calculating disease rates. NAHDO Conference 2020. Virtual, August 25, 2020. 
* Stamm, A (2021). Introduction to Pathways. District 53 Toastmasters Leadership Institute. Schenectady, NY, July 13, 2018.
* Stamm, A, & Babcock, G (2021). gatpkg: Geographic Aggregation Tool (GAT). R package version 1.61.0. https://github.com/ajstamm/gatpkg
*	Stamm, A, Savadatti, S, Kumar, S, & Hwang, S (2017). A spatial analysis of acute myocardial infarction rates in New York State in relation to hospitals along state jurisdictional borders. Journal Of Public Health Management And Practice, 23(5), S39-S44. doi:10.1097/PHH.0000000000000596

---

### AWARDS

* Toastmasters International: Competent Communicator, Advanced Communicator Bronze, Competent Leader, Advanced Leader Bronze
* Commissioner's Recognition Award for Inter-Agency or Intra-Agency Cooperation, Governor's Cancer Research Initiative Team, NYS Department of Health, December 2019

